// config.bin - 10:23:53 11/26/23, generated in 0.00 seconds
// Generated by unRap v1.06 by Kegetys
// Separate rootclasses: Disabled, Automatic comments: Enabled

class CfgPatches {
	class VOS_Radio3 {
		units[] = {"VOS_RadioPanasonic"};
		weapons[] = {};
		requiredVersion = 0.1;
		requiredAddons[] = {"DZ_Gear_Containers", "DZ_Gear_Crafting", "DZ_Gear_Tools", "DZ_Scripts"};
	};
};

class CfgVehicles {
	class VOS_Radio;	// External class reference
	
	class VOS_RadioPanasonic : VOS_Radio {
		scope = 2;
		displayName = "Panasonic RF-2400D";
		descriptionShort = "$STR_Radio3_desc";
		animClass = "Knife";
		attachments[] = {"BatteryD", "Cassette"};
		fragility = 0.01;
		varWetMax = 0.35;
		repairableWithKits[] = {5, 7};
		repairCosts[] = {50, 55};
		model = "VOS_Radio\Radio\Panasonic\VOSPanasonic.p3d";
		weight = 1700;
		itemSize[] = {2, 2};
		
		class DamageSystem {
			class GlobalHealth {
				class Health {
					hitpoints = 100;
					healthLevels[] = {{1.0, {"VOS_Radio\Radio\Panasonic\data\Panasonic.rvmat"}}, {0.7, {"VOS_Radio\Radio\Panasonic\data\Panasonic.rvmat"}}, {0.5, {"VOS_Radio\Radio\Panasonic\data\Panasonic_damage.rvmat"}}, {0.3, {"VOS_Radio\Radio\Panasonic\data\Panasonic_damage.rvmat"}}, {0.0, {"VOS_Radio\Radio\Panasonic\data\Panasonic_destruct.rvmat"}}};
				};
			};
		};
		
		class EnergyManager {
			hasIcon = 1;
			autoSwitchOff = 1;
			autoSwitchOffWhenInCargo = 0;
			plugType = 1;
			energyUsagePerSecond = 0.001;
			attachmentAction = 1;
			wetnessExposure = 0.12;
		};
		
		class MeleeModes {
			class Default {
				ammo = "MeleeLightBlunt";
				range = 1;
			};
			
			class Heavy {
				ammo = "MeleeLightBlunt_Heavy";
				range = 1;
			};
			
			class Sprint {
				ammo = "MeleeLightBlunt_Heavy";
				range = 2.8;
			};
		};
	};
};
