// config.bin - 20:56:49 11/29/23, generated in 0.00 seconds
// Generated by unRap v1.06 by Kegetys
// Separate rootclasses: Disabled, Automatic comments: Enabled

class CfgPatches {
	class VOS_Radio {
		units[] = {};
		weapons[] = {};
		requiredVersion = 1;
		requiredAddons[] = {"DZ_Data", "DZ_Radio", "DZ_Gear_Tools", "DZ_Characters", "DZ_Scripts"};
	};
};

class CfgMods {
	class VOS_Radio {
		dir = "VOS_Radio";
		name = "VOS_Radio";
		credits = "Voster";
		author = "Voster";
		authorID = ;
		version = 1.0;
		extra = 0;
		type = "mod";
		inputs = "VOS_Radio/inputs.xml";
		dependencies[] = {"Game", "World", "Mission"};
		
		class defs {
			class imageSets {
				files[] = {"VOS_Radio/gui/imagesets/vos_rad.imageset"};
			};
			
			class gameScriptModule {
				value = "";
				files[] = {"VOS_Radio/scripts/common", "VOS_Radio/scripts/3_Game"};
			};
			
			class worldScriptModule {
				value = "";
				files[] = {"VOS_Radio/scripts/common", "VOS_Radio/scripts/4_World"};
			};
			
			class missionScriptModule {
				value = "";
				files[] = {"VOS_Radio/scripts/common", "VOS_Radio/scripts/5_Mission"};
			};
		};
	};
};
